// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using test2Proba.Models;

#nullable disable

namespace test2Proba.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20230528132634_initialMigration22")]
    partial class initialMigration22
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("test2Proba.Models.BreedType", b =>
                {
                    b.Property<int>("IdBreedType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBreedType"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBreedType");

                    b.ToTable("BreedType");
                });

            modelBuilder.Entity("test2Proba.Models.Pet", b =>
                {
                    b.Property<int>("IdPet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPet"));

                    b.Property<DateTime>("ApproximateDateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("BreedTypeIdBreedType")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdopted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRegistered")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdBreedType")
                        .HasColumnType("int");

                    b.Property<bool>("IsMale")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPet");

                    b.HasIndex("BreedTypeIdBreedType");

                    b.ToTable("Pet");
                });

            modelBuilder.Entity("test2Proba.Models.Volunteer", b =>
                {
                    b.Property<int>("IdVolunteer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVolunteer"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdSupervisor")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVolunteer");

                    b.HasIndex("IdSupervisor");

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("test2Proba.Models.VolunteerPet", b =>
                {
                    b.Property<int>("IdVolunteer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVolunteer"));

                    b.Property<DateTime>("DateAccepted")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPet")
                        .HasColumnType("int");

                    b.Property<int>("PetIdPet")
                        .HasColumnType("int");

                    b.Property<int>("VolunteerIdVolunteer")
                        .HasColumnType("int");

                    b.HasKey("IdVolunteer");

                    b.HasIndex("PetIdPet");

                    b.HasIndex("VolunteerIdVolunteer");

                    b.ToTable("VolunteerPets");
                });

            modelBuilder.Entity("test2Proba.Models.Pet", b =>
                {
                    b.HasOne("test2Proba.Models.BreedType", "BreedType")
                        .WithMany("Pets")
                        .HasForeignKey("BreedTypeIdBreedType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BreedType");
                });

            modelBuilder.Entity("test2Proba.Models.Volunteer", b =>
                {
                    b.HasOne("test2Proba.Models.Volunteer", "Supervisor")
                        .WithMany("Subordinates")
                        .HasForeignKey("IdSupervisor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("test2Proba.Models.VolunteerPet", b =>
                {
                    b.HasOne("test2Proba.Models.Pet", "Pet")
                        .WithMany("VolunteerPets")
                        .HasForeignKey("PetIdPet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("test2Proba.Models.Volunteer", "Volunteer")
                        .WithMany("VolunteerPets")
                        .HasForeignKey("VolunteerIdVolunteer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("test2Proba.Models.BreedType", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("test2Proba.Models.Pet", b =>
                {
                    b.Navigation("VolunteerPets");
                });

            modelBuilder.Entity("test2Proba.Models.Volunteer", b =>
                {
                    b.Navigation("Subordinates");

                    b.Navigation("VolunteerPets");
                });
#pragma warning restore 612, 618
        }
    }
}
